#!/usr/bin/env node

/**
 * Build script for Vercel deployment
 * Injects environment variables into config.js
 */

const fs = require("fs");
const path = require("path");

// Get API_BASE from environment variable or use default
const API_BASE = process.env.REACT_APP_API_BASE || "http://localhost:8000";

console.log("🔨 Building frontend configuration...");
console.log("📍 REACT_APP_API_BASE env var:", process.env.REACT_APP_API_BASE);
console.log("📍 Final API_BASE:", API_BASE);

// Generate config.js with injected environment variables
const configContent = `// Configuration injected at build time
// DO NOT EDIT - This file is auto-generated by build.js

(function() {
  if (!window.__CONFIG__) {
    window.__CONFIG__ = {};
  }
  
  window.__CONFIG__.api_base = '${API_BASE}';
  
  console.log('✓ Configuration loaded:', window.__CONFIG__);
  console.log('  API Base URL:', window.__CONFIG__.api_base);
})();
`;

// Write config.js to frontend directory
const configPath = path.join(__dirname, "config.js");

try {
  fs.writeFileSync(configPath, configContent, "utf8");
  console.log("✓ config.js generated successfully");
  console.log("📄 Location:", configPath);
  console.log("📝 Content length:", configContent.length, "bytes");
  console.log("");

  // Verify file was written
  const written = fs.readFileSync(configPath, "utf8");
  if (written.includes(API_BASE)) {
    console.log("✓ Verification: config.js contains correct API_BASE");
  } else {
    console.error(
      "✗ Verification FAILED: config.js does not contain API_BASE!",
    );
    process.exit(1);
  }
} catch (err) {
  console.error("✗ Error writing config.js:", err.message);
  process.exit(1);
}
